# Generated by Django 3.2.19 on 2023-05-27 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20230527_1641'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
