# Generated by Django 3.2.19 on 2023-05-29 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_delete_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
    ]
